---
- name: Configure Apache.
  lineinfile:
    dest: "{{ apache_server_root }}/conf/{{ apache_daemon }}.conf"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items: "{{ apache_ports_configuration_items }}"
  notify: restart apache

- name: Configure SSL Apache.
  lineinfile:
    dest: "{{ apache_server_root }}/conf/{{ apache_daemon }}.conf"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    insertafter: "{{ item.regexp }}"
    state: present
  with_items: "{{ apache_ssl_ports_configuration_items }}"
  notify: restart apache
  when: apache_create_ssl_vhosts


- name: Create SSL Cert File.
  template:
    src: server-cert.pem.j2
    dest: "{{ apache_conf_path }}/{{ item.certificate_file }}"
    owner: root
    group: root
    mode: 0644
  with_items: "{{ apache_vhosts_ssl }}"
  notify: restart apache
  when: apache_create_ssl_vhosts

- name: Create SSL Cert Key File.
  template:
    src: server-rsa-key.pem.j2
    dest: "{{ apache_conf_path }}/{{ item.certificate_key_file }}"
    owner: root
    group: root
    mode: 0644
  with_items: "{{ apache_vhosts_ssl }}"
  notify: restart apache
  when: apache_create_ssl_vhosts

- name: Check whether certificates defined in vhosts exist.
  stat: path="{{ apache_conf_path }}/{{ item.certificate_file }}"
  register: apache_ssl_certificates
  with_items: "{{ apache_vhosts_ssl }}"
  when: apache_create_ssl_vhosts

- name: Add apache vhosts configuration.
  template:
    src: "{{ apache_vhosts_template }}"
    dest: "{{ apache_conf_path }}/{{ apache_vhosts_filename }}"
    owner: root
    group: root
    mode: 0644
  notify: restart apache
  when: apache_create_vhosts

- name: Remove Default ssl configuration
  file:
    path: "{{ apache_conf_path }}/ssl.conf"
    state: absent
  when: apache_create_ssl_vhosts