---

- name: Provision Stack 
  hosts: localhost
  connection: local
  gather_facts: False
  vars_files:
    - "vars/common.yaml"
    - "vars/{{ stack }}/cloudformation.yaml"
  roles:
    - "{{ stack }}"
